final List<Map<String, dynamic>> products = [
  {
    'category': 'Sneakers',
    'title': 'Nike Air Max 200',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 240.0,
    'imageUrl': 'images/shose.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Sneakers',
    'title': 'Mesh',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 240.0,
    'imageUrl': 'images/mesh.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Sneakers',
    'title': 'Canvas',
    'price': 280.0,
    'imageUrl': 'images/Canvas.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Sneakers',
    'title': 'Cork',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 240.0,
    'imageUrl': 'images/cort.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Sneakers',
    'title': 'Leather',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 240.0,
    'imageUrl': 'images/leather shose.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Sneakers',
    'title': 'Cotton',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 220.0,
    'imageUrl': 'images/cotton 2.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Jacket',
    'title': 'Winter Jacket',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 150.0,
    'imageUrl': 'images/winter.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Jacket',
    'title': 'Leather Jacket',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 180.0,
    'imageUrl': 'images/leather.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Jacket',
    'title': 'Denim Jacket',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 180.0,
    'imageUrl': 'images/denim.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Jacket',
    'title': 'Raincoat',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 140.0,
    'imageUrl': 'images/raincoat1.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Jacket',
    'title': 'Blazer',
    'description': 'Perfect for cold weather.',
    'rating': 4.7,
    'price': 190.0,
    'imageUrl': 'images/blazer.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Jacket',
    'title': 'Trench Coat',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 180.0,
    'imageUrl': 'images/Trenchcoat.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Watch',
    'title': 'Rolex Watch',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 500.0,
    'imageUrl': 'images/w2.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Watch',
    'title': 'Casio Watch',
    'description': 'Perfect for cold weather.',
    'rating': 3.2,
    'price': 120.0,
    'imageUrl': 'images/rolx.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Watch',
    'title': 'Aviator Watch',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 120.0,
    'imageUrl': 'images/aviator.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Watch',
    'title': 'Smart Watch',
    'price': 160.0,
    'description': 'Perfect for cold weather.',
    'rating': 2.2,
    'imageUrl': 'images/smart Watch.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Watch',
    'title': 'Digital Watch',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 120.0,
    'imageUrl': 'images/digital.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Watch',
    'title': 'Quartz Watch',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 120.0,
    'imageUrl': 'images/Quartz.jpg',
    'count_of_product': 10,
  },
];
